(() => {
  'use strict';
  const canvas = document.getElementById('view');
  const gl = canvas.getContext('webgl', { antialias: false, alpha: false, powerPreference: 'high-performance' });
  if (!gl) { document.body.innerHTML = '<p style="padding:2rem;color:white">This game needs a browser with WebGL support.</p>'; return; }
  const chunkSize = 16, maxChunks = 100, renderRadius = 4, reach = 3;
  const gravity = 20, jumpVelocity = 9.2;
  const types = [
    { name: 'Grass', color: [0.39,0.57,0.31], hint: 'Blocks grow best outside.' },
    { name: 'Dirt', color: [0.48,0.36,0.23], hint: 'A little earth goes a long way.' },
    { name: 'Stone', color: [0.48,0.49,0.45], hint: 'A solid foundation.' },
    { name: 'Sand', color: [0.77,0.67,0.43], hint: 'A warmer kind of ground.' },
    { name: 'Wood', color: [0.47,0.30,0.15], hint: 'Make something that feels like home.' }
  ];
  const blockNames = ['air','grass','dirt','stone','sand','wood'];
  const blockId = { grass:1,dirt:2,stone:3,sand:4,wood:5 };
  const inventory = [10,10,10,10,10];
  let selected = 0, chunks = new Map(), seed = 267931, lastTime = 0, acc = 0, dirtyMeshes = new Set();
  const chunkEdits = new Map();
  let running = false, pointerLocked = false, muted = false, audio = null, toastTimer = 0;
  const player = { x: 8, y: 30, z: 8, vx: 0, vy: 0, vz: 0, yaw: 0, pitch: 0, grounded: false, step: 0 };
  const keys = new Set();

  const vertexShader = `attribute vec3 aPosition; attribute vec3 aColor; uniform mat4 uView; uniform mat4 uProjection; varying vec3 vColor; void main(){vColor=aColor;gl_Position=uProjection*uView*vec4(aPosition,1.0);}`;
  const fragmentShader = `precision mediump float; varying vec3 vColor; void main(){gl_FragColor=vec4(vColor,1.0);}`;
  function shader(type, source) { const s=gl.createShader(type); gl.shaderSource(s,source); gl.compileShader(s); if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)) throw Error(gl.getShaderInfoLog(s)); return s; }
  const program = gl.createProgram(); gl.attachShader(program,shader(gl.VERTEX_SHADER,vertexShader)); gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragmentShader)); gl.linkProgram(program);
  if(!gl.getProgramParameter(program,gl.LINK_STATUS)) throw Error(gl.getProgramInfoLog(program));
  gl.useProgram(program);
  const loc = { pos:gl.getAttribLocation(program,'aPosition'), color:gl.getAttribLocation(program,'aColor'), view:gl.getUniformLocation(program,'uView'), projection:gl.getUniformLocation(program,'uProjection') };
  gl.enable(gl.DEPTH_TEST); gl.depthFunc(gl.LEQUAL); gl.disable(gl.CULL_FACE);

  function hash2(x,z) { let n=(Math.imul(x,374761393)+Math.imul(z,668265263)+seed)|0; n=Math.imul(n^(n>>>13),1274126177); return ((n^(n>>>16))>>>0)/4294967295; }
  function smoothNoise(x,z,scale) { const fx=x/scale,fz=z/scale,ix=Math.floor(fx),iz=Math.floor(fz),u=fx-ix,v=fz-iz; const sm=t=>t*t*(3-2*t); const a=hash2(ix,iz),b=hash2(ix+1,iz),c=hash2(ix,iz+1),d=hash2(ix+1,iz+1); return (a+(b-a)*sm(u))*(1-sm(v))+(c+(d-c)*sm(u))*sm(v); }
  function surface(x,z) { return Math.floor(8 + smoothNoise(x,z,42)*7 + smoothNoise(x+177,z-59,15)*4 + Math.sin(x*.085+z*.043)*1.5); }
  function caveAt(x,y,z) { if(y>surface(x,z)-3 || y<2) return false; const n=Math.sin(x*.21+y*.24)*.34+Math.sin(z*.23-y*.18)*.31+Math.sin((x+z+y)*.13)*.28; return n>.64 && hash2(Math.floor(x/3)+y*17,Math.floor(z/3)-y*7)>.27; }
  function key2(cx,cz){return `${cx},${cz}`;}
  function getChunk(cx,cz,create=true) { const k=key2(cx,cz); let c=chunks.get(k); if(!c&&create){c=generateChunk(cx,cz);chunks.set(k,c);dirtyMeshes.add(k);for(const [nx,nz] of [[cx-1,cz],[cx+1,cz],[cx,cz-1],[cx,cz+1]]){const neighbor=chunks.get(key2(nx,nz));if(neighbor)dirtyMeshes.add(key2(nx,nz));}while(chunks.size>maxChunks){let farKey=null,far=-1;for(const [kk,cc] of chunks){const d=(cc.cx-player.x/chunkSize)**2+(cc.cz-player.z/chunkSize)**2;if(d>far){far=d;farKey=kk;}}if(farKey===k)break; const old=chunks.get(farKey); if(old&&old.buffer)gl.deleteBuffer(old.buffer);chunks.delete(farKey);dirtyMeshes.delete(farKey);}}return c; }
  function generateChunk(cx,cz) { const blocks=new Uint8Array(chunkSize*40*chunkSize); const c={cx,cz,blocks,buffer:null,count:0}; for(let lx=0;lx<chunkSize;lx++)for(let lz=0;lz<chunkSize;lz++){const x=cx*chunkSize+lx,z=cz*chunkSize+lz,h=surface(x,z),beach=h<10; for(let y=0;y<=h;y++){if(caveAt(x,y,z))continue;let id;if(y===h)id=beach?4:1;else if(y>=h-3)id=beach?4:2;else id=3;c.blocks[index(lx,y,lz)]=id;}}const edits=chunkEdits.get(key2(cx,cz));if(edits)for(const [blockIndex,id] of edits)c.blocks[blockIndex]=id;return c; }
  function index(x,y,z){return (y*chunkSize+z)*chunkSize+x;}
  function getBlock(x,y,z,create=true){if(y<0)return 3;if(y>=40)return 0;const cx=Math.floor(x/chunkSize),cz=Math.floor(z/chunkSize),c=getChunk(cx,cz,create);return c?c.blocks[index(x-cx*chunkSize,y,z-cz*chunkSize)]:0;}
  function setBlock(x,y,z,id){if(y<0||y>=40)return;const cx=Math.floor(x/chunkSize),cz=Math.floor(z/chunkSize),c=getChunk(cx,cz),k=key2(cx,cz),blockIndex=index(x-cx*chunkSize,y,z-cz*chunkSize);c.blocks[blockIndex]=id;let edits=chunkEdits.get(k);if(!edits){edits=new Map();chunkEdits.set(k,edits);}edits.set(blockIndex,id);dirtyMeshes.add(k);if(x%chunkSize===0)dirtyMeshes.add(key2(cx-1,cz));if(x%chunkSize===chunkSize-1)dirtyMeshes.add(key2(cx+1,cz));if(z%chunkSize===0)dirtyMeshes.add(key2(cx,cz-1));if(z%chunkSize===chunkSize-1)dirtyMeshes.add(key2(cx,cz+1)); }
  const faces=[{n:[1,0,0],v:[[1,0,0],[1,1,0],[1,1,1],[1,0,0],[1,1,1],[1,0,1]],light:.82},{n:[-1,0,0],v:[[0,0,1],[0,1,1],[0,1,0],[0,0,1],[0,1,0],[0,0,0]],light:.72},{n:[0,1,0],v:[[0,1,1],[1,1,1],[1,1,0],[0,1,1],[1,1,0],[0,1,0]],light:1},{n:[0,-1,0],v:[[0,0,0],[1,0,0],[1,0,1],[0,0,0],[1,0,1],[0,0,1]],light:.52},{n:[0,0,1],v:[[1,0,1],[1,1,1],[0,1,1],[1,0,1],[0,1,1],[0,0,1]],light:.77},{n:[0,0,-1],v:[[0,0,0],[0,1,0],[1,1,0],[0,0,0],[1,1,0],[1,0,0]],light:.68}];
  function buildMesh(c){const verts=[],colors=[];for(let y=0;y<40;y++)for(let z=0;z<chunkSize;z++)for(let x=0;x<chunkSize;x++){const id=c.blocks[index(x,y,z)];if(!id)continue;const wx=c.cx*chunkSize+x,wz=c.cz*chunkSize+z,coveredAbove=getBlock(wx,y+1,wz,false)>0;for(const f of faces){if(getBlock(wx+f.n[0],y+f.n[1],wz+f.n[2],false))continue;let shade=f.light;if(coveredAbove)shade*=.72;const base=types[id-1].color,variation=.94+hash2(wx+y*11,wz-y*7)*.1;for(const v of f.v){verts.push(wx+v[0],y+v[1],wz+v[2]);colors.push(base[0]*shade*variation,base[1]*shade*variation,base[2]*shade*variation);}}}if(c.buffer)gl.deleteBuffer(c.buffer);c.buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,c.buffer);const data=new Float32Array(verts.length+colors.length);data.set(verts);data.set(colors,verts.length);c.vertexFloatCount=verts.length;c.count=verts.length/3;gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);}
  function updateMeshes(){if(!dirtyMeshes.size)return;let budget=1;for(const k of dirtyMeshes){const c=chunks.get(k);if(c)buildMesh(c);dirtyMeshes.delete(k);if(--budget<=0)break;}}

  function perspective(fovy,aspect,near,far){const f=1/Math.tan(fovy/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
  function viewMatrix(ex,ey,ez,cx,cy,cz){let zx=ex-cx,zy=ey-cy,zz=ez-cz,l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=zz,xy=0,xz=-zx;l=Math.hypot(xx,xy,xz)||1;xx/=l;xy/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;return new Float32Array([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*ex+xy*ey+xz*ez),-(yx*ex+yy*ey+yz*ez),-(zx*ex+zy*ey+zz*ez),1]);}
  function resize(){const dpr=Math.min(devicePixelRatio||1,1.5),w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h);}}
  function draw(){resize();const eyeY=player.y+1.7,dirX=Math.sin(player.yaw)*Math.cos(player.pitch),dirY=Math.sin(player.pitch),dirZ=-Math.cos(player.yaw)*Math.cos(player.pitch);gl.clearColor(.57,.73,.79,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(loc.projection,false,perspective(110*Math.PI/180,canvas.width/canvas.height,.06,220));gl.uniformMatrix4fv(loc.view,false,viewMatrix(player.x,eyeY,player.z,player.x+dirX,eyeY+dirY,player.z+dirZ));const pcx=Math.floor(player.x/chunkSize),pcz=Math.floor(player.z/chunkSize);for(let dz=-renderRadius;dz<=renderRadius;dz++)for(let dx=-renderRadius;dx<=renderRadius;dx++){if(dx*dx+dz*dz>renderRadius*renderRadius+2)continue;const c=chunks.get(key2(pcx+dx,pcz+dz));if(!c||!c.count||dirtyMeshes.has(key2(c.cx,c.cz)))continue;gl.bindBuffer(gl.ARRAY_BUFFER,c.buffer);gl.enableVertexAttribArray(loc.pos);gl.vertexAttribPointer(loc.pos,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(loc.color);gl.vertexAttribPointer(loc.color,3,gl.FLOAT,false,0,c.vertexFloatCount*4);gl.drawArrays(gl.TRIANGLES,0,c.count);}}

  function collides(x,y,z){const minX=Math.floor(x-.3),maxX=Math.floor(x+.3),minY=Math.floor(y+.001),maxY=Math.floor(y+1.999),minZ=Math.floor(z-.3),maxZ=Math.floor(z+.3);for(let bx=minX;bx<=maxX;bx++)for(let by=minY;by<=maxY;by++)for(let bz=minZ;bz<=maxZ;bz++)if(getBlock(bx,by,bz))return true;return false;}
  function moveAxis(axis,amount){if(!amount)return;const steps=Math.ceil(Math.abs(amount)/.18),step=amount/steps;for(let i=0;i<steps;i++){const x=player.x+(axis==='x'?step:0),y=player.y+(axis==='y'?step:0),z=player.z+(axis==='z'?step:0);if(!collides(x,y,z)){player.x=x;player.y=y;player.z=z;}else{if(axis==='y'){if(step<0)player.grounded=true;player.vy=0;}else if(player.grounded){const up=collides(x,player.y+1.01,z);if(!up){player.y+=1;player.x=x;player.z=z;}else if(collides(x,player.y,z)){if(axis==='x')player.vx=0;else player.vz=0;}}else{if(axis==='x')player.vx=0;else player.vz=0;}break;}}}
  function update(dt){const forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),side=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),mag=Math.hypot(forward,side)||1,run=keys.has('ShiftLeft')||keys.has('ShiftRight'),speed=run?8:4.6;const fx=Math.sin(player.yaw),fz=-Math.cos(player.yaw),rx=Math.cos(player.yaw),rz=Math.sin(player.yaw);const tx=((fx*forward+rx*side)/mag)*speed,tz=((fz*forward+rz*side)/mag)*speed;const smoothing=1-Math.exp(-12*dt);player.vx+=(tx-player.vx)*smoothing;player.vz+=(tz-player.vz)*smoothing;moveAxis('x',player.vx*dt);moveAxis('z',player.vz*dt);player.grounded=false;player.vy=Math.max(player.vy-gravity*dt,-35);moveAxis('y',player.vy*dt);if(player.y< -5){player.x=8;player.z=8;player.y=surface(8,8)+2;player.vy=0;}if(Math.hypot(player.vx,player.vz)>.6&&player.grounded){player.step+=dt*(run?8:5);if(player.step>0.47){player.step=0;sound('step');}}const px=Math.floor(player.x),py=Math.floor(player.y),pz=Math.floor(player.z);document.getElementById('coords').textContent=`${px}, ${py}, ${pz}`;document.getElementById('ground-status').textContent=player.grounded?'ON SOLID GROUND':'IN THE AIR';}
  function raycast(){const ox=player.x,oy=player.y+1.62,oz=player.z,dx=Math.sin(player.yaw)*Math.cos(player.pitch),dy=Math.sin(player.pitch),dz=-Math.cos(player.yaw)*Math.cos(player.pitch);let x=Math.floor(ox),y=Math.floor(oy),z=Math.floor(oz);const sx=Math.sign(dx),sy=Math.sign(dy),sz=Math.sign(dz),ddx=dx?Math.abs(1/dx):Infinity,ddy=dy?Math.abs(1/dy):Infinity,ddz=dz?Math.abs(1/dz):Infinity;let mx=dx>0?(x+1-ox)*ddx:(ox-x)*ddx,my=dy>0?(y+1-oy)*ddy:(oy-y)*ddy,mz=dz>0?(z+1-oz)*ddz:(oz-z)*ddz,prev=null,t=0;for(let i=0;i<32&&t<=reach;i++){if(getBlock(x,y,z))return {x,y,z,prev};prev={x,y,z};if(mx<my&&mx<mz){x+=sx;t=mx;mx+=ddx;}else if(my<mz){y+=sy;t=my;my+=ddy;}else{z+=sz;t=mz;mz+=ddz;}}return null;}
  function placeOrBreak(remove){const hit=raycast();if(!hit){if(!remove)toast('No block within reach');return;}if(remove){const id=getBlock(hit.x,hit.y,hit.z);if(!id)return;setBlock(hit.x,hit.y,hit.z,0);if(id>=1&&id<=5)inventory[id-1]++;sound('break');renderHotbar();toast(`${blockNames[id][0].toUpperCase()+blockNames[id].slice(1)} collected`);}else{const x=hit.prev.x,y=hit.prev.y,z=hit.prev.z,id=selected+1;if(inventory[selected]<=0){toast('No blocks left in this slot');return;}if(getBlock(x,y,z)||playerOverlapsBlock(x,y,z)){toast('There isn’t room to place that');return;}setBlock(x,y,z,id);inventory[selected]--;sound('place');renderHotbar();}}
  function playerOverlapsBlock(x,y,z){return player.x+.3>x&&player.x-.3<x+1&&player.z+.3>z&&player.z-.3<z+1&&player.y+2>y&&player.y<y+1;}
  function renderHotbar(){const bar=document.getElementById('hotbar');bar.innerHTML='';types.forEach((type,i)=>{const slot=document.createElement('button');slot.className='slot'+(selected===i?' selected':'');slot.setAttribute('aria-label',`${i+1}: ${type.name}, ${inventory[i]} blocks`);slot.innerHTML=`<span class="number">${i+1}</span><span class="block-icon ${type.name.toLowerCase()}"></span><span class="count">${inventory[i]}</span>`;slot.addEventListener('click',()=>selectSlot(i));bar.appendChild(slot);});document.getElementById('selected-name').textContent=types[selected].name;document.getElementById('selected-hint').textContent=types[selected].hint;}
  function selectSlot(i){selected=i;renderHotbar();}
  function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1200);}
  function sound(kind){if(muted)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);const params={step:[105,.035,'sine'],jump:[210,.13,'triangle'],break:[150,.11,'square'],place:[330,.12,'triangle']}[kind];osc.type=params[2];osc.frequency.setValueAtTime(params[0],now);osc.frequency.exponentialRampToValueAtTime(params[0]*(kind==='break'?.52:1.45),now+params[1]);gain.gain.setValueAtTime(kind==='step'?.025:.045,now);gain.gain.exponentialRampToValueAtTime(.001,now+params[1]);osc.start(now);osc.stop(now+params[1]);}catch(_){} }
  function startGame(){running=true;document.getElementById('start-screen').classList.add('dismissed');document.getElementById('pause-screen').classList.add('hidden');canvas.requestPointerLock?.();const tx=Math.floor(player.x),tz=Math.floor(player.z);player.y=surface(tx,tz)+1.02;getChunk(0,0);}
  function enterPause(){if(document.pointerLockElement===canvas)document.exitPointerLock();if(running)document.getElementById('pause-screen').classList.remove('hidden');}
  document.getElementById('play-button').addEventListener('click',startGame);document.getElementById('resume-button').addEventListener('click',()=>{document.getElementById('pause-screen').classList.add('hidden');canvas.requestPointerLock?.();});
  document.getElementById('dismiss-hint').addEventListener('click',()=>document.getElementById('hint-card').style.display='none');document.getElementById('sound-toggle').addEventListener('click',e=>{muted=!muted;e.currentTarget.innerHTML=muted?'♫ <span>Sound off</span>':'♫ <span>Sound on</span>';});
  document.addEventListener('pointerlockchange',()=>{pointerLocked=document.pointerLockElement===canvas;if(!pointerLocked&&running)document.getElementById('pause-screen').classList.remove('hidden');});
  document.addEventListener('mousemove',e=>{if(!pointerLocked)return;player.yaw-=e.movementX*.0025;player.pitch=Math.max(-1.48,Math.min(1.48,player.pitch-e.movementY*.0025));});
  document.addEventListener('keydown',e=>{keys.add(e.code);if(/^Digit[1-5]$/.test(e.code))selectSlot(Number(e.code.slice(-1))-1);if(e.code==='Space'){e.preventDefault();if(player.grounded&&running){player.vy=jumpVelocity;player.grounded=false;sound('jump');}}if(e.code==='Escape'&&running)enterPause();});document.addEventListener('keyup',e=>keys.delete(e.code));
  canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('mousedown',e=>{if(!running||!pointerLocked)return;if(e.button===2||(e.button===0&&(e.shiftKey||keys.has('ShiftLeft')||keys.has('ShiftRight'))))placeOrBreak(true);else if(e.button===0)placeOrBreak(false);});document.addEventListener('pointerdown',e=>{if(running&&!pointerLocked&&!e.target.closest('button')&&!document.getElementById('pause-screen').classList.contains('hidden'))canvas.requestPointerLock?.();});
  function ensureNearbyChunks(){const cx=Math.floor(player.x/chunkSize),cz=Math.floor(player.z/chunkSize),missing=[];for(let dz=-renderRadius;dz<=renderRadius;dz++)for(let dx=-renderRadius;dx<=renderRadius;dx++){if(dx*dx+dz*dz>renderRadius*renderRadius+2||chunks.has(key2(cx+dx,cz+dz)))continue;missing.push([dx*dx+dz*dz,cx+dx,cz+dz]);}missing.sort((a,b)=>a[0]-b[0]);for(let i=0;i<Math.min(2,missing.length);i++)getChunk(missing[i][1],missing[i][2]);}
  function frame(now){const dt=Math.min((now-lastTime)/1000||0,.05);lastTime=now;if(running&&pointerLocked){acc+=dt;while(acc>=1/60){update(1/60);acc-=1/60;}}ensureNearbyChunks();updateMeshes();draw();requestAnimationFrame(frame);}
  // Start with one nearby chunk and fill the view a little at a time.
  player.x=8;player.z=8;player.y=surface(8,8)+1.02;getChunk(0,0);renderHotbar();requestAnimationFrame(frame);
})();
